name: Hello World Workflow

on: [push]

jobs:
  # self-hosted-job:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print Hello World
  #       run: echo "Hello World"
  #     - run: curl -O https://jit-cli.s3.us-east-1.amazonaws.com/jit-cli/sc-29437-test-our-solution-on-various-machines/jit-cli-amd64-slim
  #     - run: chmod +x jit-cli-amd64-slim
  #     - name: Run CLI with env vars
  #       env:
  #         JIT_CLIENT_ID: ${{ secrets.JIT_CLIENT_ID }}
  #         JIT_SECRET_KEY: ${{ secrets.JIT_SECRET_KEY }}
  #         ENV_NAME: bandit
  #       run: ./jit-cli-amd64-slim container --image python:3.10-alpine3.16
  # github-hosted-job-podman:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Print Hello World
  #       run: echo "Hello World"
  #     - name: Install Podman
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y podman
  #     - name: Build Docker image
  #       run: podman build -t hello-world-container -f podman-demo/Dockerfile .
  #     - name: Save image to tar
  #       run: podman save hello-world-container -o image.tar
  #     - run: curl -O https://jit-cli.s3.us-east-1.amazonaws.com/jit-cli/main/jit-cli-amd64-slim
  #     - run: chmod +x jit-cli-amd64-slim
  #     - name: Run CLI with env vars
  #       env:
  #         JIT_CLIENT_ID: ${{ secrets.JIT_CLIENT_ID }}
  #         JIT_SECRET_KEY: ${{ secrets.JIT_SECRET_KEY }}
  #         ENV_NAME: bandit
  #       run: ./jit-cli-amd64-slim container --image image.tar --tracking-name ohav-registry/ohav-image-github-hosted-runner --fail-on-findings

  # github-hosted-job-alpine:
  #   runs-on: ubuntu-latest
  #   container: alpine:latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Print Hello World
  #       run: echo "Hello World"
  #     - name: Install curl
  #       run: apk add --no-cache curl
  #     - name: Install git
  #       run: apk add --no-cache git
  #     - run: curl -O https://jit-cli.s3.us-east-1.amazonaws.com/jit-cli/main/jit-cli-amd64-alpine
  #     - run: chmod +x jit-cli-amd64-alpine
  #     - name: Run CLI with env vars
  #       env:
  #         JIT_CLIENT_ID: ${{ secrets.JIT_CLIENT_ID }}
  #         JIT_SECRET_KEY: ${{ secrets.JIT_SECRET_KEY }}
  #         ENV_NAME: bandit
  #       run: ./jit-cli-amd64-alpine container --image python:3.10-slim-bullseye --tracking-name ohav-registry/ohav-image-github-hosted-runner-2

  github-hosted-job-simple-python-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: curl -O https://jit-cli.s3.us-east-1.amazonaws.com/jit-cli/sc-29391-cli-tool-jit-cli-create-the-jit-container-2/jit-cli-amd64-slim
      - run: chmod +x jit-cli-amd64-slim
      - name: Run CLI with env vars
        env:
          JIT_CLIENT_ID: ${{ secrets.JIT_CLIENT_ID }}
          JIT_SECRET_KEY: ${{ secrets.JIT_SECRET_KEY }}
          ENV_NAME: bandit
        run: ./jit-cli-amd64-slim container --image python:3.10-slim-bullseye --tracking-name reg/img-5
